=== Setmana 4

==== David
Millorar el ProductControler. Utilitzar sessió per les variables del $Request.
Temps estimat => 2h
Temps Real => 3h

Carret amb productes no únics
Temps estimats => 3h
Temps real => 6h

Passar múltiples variables i repetició de codi en cada Controller a variables de sessió, utilitzant el component 'Header'.
Temps estimats => 2h
Temps real => 2h

Resoldre conflictes
Temps real => 1:30h

Carret amb productes únics
Temps estimat => 1h
Temps real => 1:30h

Mantenir el carret a l'hora de recargar la pàgina i re-utilitzar funcions de javascript (amb mòduls) per poder afegir desde la pàgina de detall del producte.
Temps estimat => 3h
Temps real => 1h

==== Oscar
Crear el disseny del register.
Temps estimat => 2h
Temps real => 2:30h

Crear el disseny del login.
Temps estimat => 2h
Temps real => 30 min

Crear disseny de la pagina de recuperació del password.
Temps estimat => 2h 
Temps real => 2h

Fer la implementació del register.
Temps estimat => 3h 
Temps real => 3h

Fer la implementació del login. 
Temps estimat => 3h 
Temps real => 2:30h

Aconseguir que envii els mails correpsondents.
Temps estimat => 3h 
Temps real => 4h

Cambiar la funció selectCategories.
Temps estimat => 1h 
Temps real => 15min

Fer la implementació de recordar la contrasenya.
Temps estimat =>3h
Temps real => 2:45h

Fer que envii els mails a tots els correus.
Temps estimat => 1h
Temps real => 20min
==== Albert

Arreglar problemes d'accesibilitat en els colors.
Temps estimat => 1h 
Temps real => 1:45h

Problemes en la versió de node i packaje.json.
Temps estimat => 2h 
Temps real => 4:30h

Actualitzar stil global.
Temps estimat => 3h 
Temps real => 4h

Millorar i simplificar estil del header.
Temps estimat => 2h 
Temps real => 2:30h

Millorar i simplificar estil del footer.
Temps estimat => 1h 
Temps real => 1h

Millorar i simplificar estil del navigation.
Temps estimat => 1h 
Temps real => 0:30h

Documentació
Temps estimat => 1h 
Temps real => 1h

=== Setmana 3

==== David
Fer la paginació completament personalitzada.
Temps estimat => 1h
Temps real => 1:30h

Modificar factory per fer tests amb accents i caràcters especials.
Temps estimat => 2h
Temps real => 1:30h

Modificar factory per utilitzar rutes físiques en comptes de URLs.
Temps estimat => 1h
Temps real => 30 min

Solucionar problema relacionat amb els inner joins amb el filtre de les categories.
Temps estimat => 2h
Temps real => 2:30h

==== Oscar

==== Albert

Actualitzar la funcionalitat del migrate:rollback per solucionar els errors que hi havia.
Temps estimat => 1h
Temps real => 2h

Investigació sobre com fer test en php
Temps estimat => 5h 
Temps real => 10h

Crear test del store amb tdd.
Temps estimat => 1h 
Temps real => 1:30h

Crida general als seeders desde el seeder general
Temps estimat => 1h 
Temps real => 1h

Documentació
Temps estimat => 1h 
Temps real => 1h


=== Setmana 2

==== David

Aquesta setmana he redissenyat la home view 3 vegades. Més que res per fer-la completament responsive i ajustar el grid correctament. La primera versió no era responsive. La segona versió tenia 6 media queries, i la tercera i última només té un media query i un grid amb un repeat amb minmax per fer-lo més automàtic. També he buscat i afegit icones, i he fet un logo pel projecte.

A més de la vista del home, he fet un component per al header, i un altre pel navigation. El navigation només es mostra per dispositius mòbils o tablets: he pensat que es una bona idea posar el navigation sota del tot per no saturar massa el header.
- Header: logo, search bar, ordenació, icona d'usuari i icona del carret
- Navigation: icona de home i icona d'usuari

La barra de resultats de cerca és funcional, he afegit una vista sense detall pel carret i el login i fet la paginació.

He afegit tipografia a la pàgina a "typografy_css", utilitzant l'arquitectura SASS.

He mirat per crear imatges aleatòries amb un factory i faig servir un fakeimg.

==== Oscar

Aquesta setmana he tingut alguns contratemps amb les migracions i els filtres.

He aconsgeuit resoldre els problemes amb la taula del mig. També he hagut de resideñar algunes migracions, per a que així pugui filtrar bé...

He fet el filtre de categories,encara que m'ha donat bastants problemes.

També he fet el filtre de tags, y que puguis filtrar per catergoria i per tag a la vegada, així com per nom del producte.

Per últim he actualitzat la guía d'estils i la documentació ja que hem redisenyar la home un altra cop.

==== Albert

Durant la setmana he realitzat les següents tasques:

- Creació de la relació n-m entre les taules.

- La creació de les migracions i seeders a la base de dades.
Elaboració de les migracions i dels seeders.

A les migracions s'afegeix l'estructura de taules i relacions que tindrà la base de dades, s'inclou també les connexions per realitzar una relació n-m entre les taules de "productes" i de "categories"

S'afegeixen els seeders que l'ompliran de dades fictícies gràcies a les factories. També s'afeixen les condicions necessàries en el mètode down() dels seeds perquè en cas de fer un migrate:rollback es desvinculin les relacions entre taules i es pugui a continuació esborrar les dades i les taules.

- L'eliminació dels fitxers que van ser inclosos en el repositori remot, i que no ho haurien d'haver estat inclosos.

L'eliminació dels fitxers .env i alguns fitxers de configuració de la màquina virtual de Vagrant per la base de dades.

Aquestes tasques es van allargar més del temps estimat.
- Creació i configuració del migrate:rollback => 2h
- Creació de la relació n-m => 5h
Entre documentació, cerca d'informació i realització de les tasques han superat el temps previst i superat el temps de les 18h de classe.

=== Setmana 1

Hem començat el projecte creant un trello per definir les tasques del projecte i organitzar-nos.
Hem creat un repositori al git de l'institut per al projecte, amb les branques principals de treball (main, development)

==== David

Començar a familiaritzar-se amb git, crear tasques de trello, instal·lar SASS i el layout main de la pàgina.

==== Oscar

Començar a familiaritzar-se amb git, crear tasques de trello, dissenyar i crear la BBDD, guia d'estil i el layout de la HomePage

==== Albert

Demostració d'ús de git a l'equip, instal·lació del laravel al projecte, creació del Vagrant per allotjar la BBDD.