=== Conclusions

Com a conclusions finals, treiem que nosaltres creiem que hem treballat molt bé, sempre ha hagut un bon ambient i a mesura que avançava el projecte hi havia més encara.

Creiem que ens hem organitzat força bé, ja que a excepció de l'ultima setmana, hem pogut arribar a tot el que ens haviem proposat fer. Si que es veritat, que creiem que a vegadas ens ha faltat comunicació a l'hora d'arribar a totes les tasques proposades, però en línies generals, ens hem organitzat bé.Ens haguès agradat tenir una mica de temps més, per a poder revisar el projecte més profundament i poder arreglar els bugs pertinents, però tot i així estem satisfets amb el treball fet.

Creiem que a mesura que ha anat avançant el projecte, ens hem fet més forts davant les adversitats que ens afrontaven, per molt que no ens surtís alguna cosa ho intentavam fins a aconseguir-ho.

Com a últim dessitg, volem agraïr tant  al professorat per ajudar-nos sempre que han pogut, com a cada membre del nostre grup per facilitar un bon ambient de treball i formar un bon equip. 